### ISSUE TITLE
Define IDs for Talon SRXs

### ISSUE THREAD

**Issue by koritzinsky** [NicoletFEAR/Steamworks-2017#10]
Description of the story:  Define which TalonSRX IDs are used for each speed controller.  This is going to be a standard that will be used for each of the robots that FEAR creates from now on.  This is a document that lists what each TalonSRX is used for (e.g. drive base, right front motor)

- [ ] Pull Request Required, none

Ready Criteria:
 * None
 * What hardware is needed? None
   

 Done Criteria:
  * A document is uploaded to the shared drive with the assignments for the TalonSRX IDs
  * The document is reviewed by Electrical Manager, Programming Manager, and Mentor

  Make sure this issue is associated with a Milestone!

**Comment by Noah-Kennedy** [comment]
I am not certain that a review by the electrical manager is necessary. I do not believe that this would have any effect on them, as CANTalon IDs are purely a software construct.

**Comment by koritzinsky** [comment]
The idea for the review is just for communication purposes so electrical understands that whenever they put on a Talon they need to know that programming has to set up the ID.  Also,  do you want electrical to to get Talons that have been set to ID=31 before we install?
