### ISSUE TITLE
SPIKE Vision

### ISSUE THREAD

**Issue by jkoritzinsky** [NicoletFEAR/Steamworks-2017#17]
Explore the new vision API and determine feasibility of vision for this year's game.

- [ ] Pull Request Required

Ready Criteria:
 * What hardware is needed?
   - Camera
 * What software is needed?
    - CameraServer Core
    - OpenCV Java

Test Cases:
 * None

 Done Criteria:
  * Have summary with code snippets for outline and feasibility

**Comment by jkoritzinsky** [comment]
To make finding the filters easier, we can must use RGB and use either Gimp or photoshops feature to get the rgb values and use those for the range.

**Comment by Lucas-Houchin-Miller** [comment]
1. Retrieving image
2. Processing image 
    - blurring image to smooth out false positives
    - filtering out colors
    - finding contours
3. Filtering Image
    - approximate polycurve to determine shape or contour
    - find area to filter out any other false positives
    -get bounding box to get orientation
From there, act on processing given by above steps.
http://wpilib.screenstepslive.com/s/3120/m/8731/l/90361-identifying-and-processing-the-targets
This link provides math to be implemented in opencv. It looks like we'll need to add data points using the camera>against the wall>tape measure method.

**Comment by richard-a-wood** [comment]
For the record we have the rgb ranges for the yellow tape image on the white board, right end.
