### ISSUE TITLE
Prevent Overshooting with NavX

### ISSUE THREAD

**Issue by Noah-Kennedy** [NicoletFEAR/Steamworks-2017#32]
Create a command to prevent the navX from overshooting. This might require PID.

- [x] Pull Request Required

Ready Criteria:
 * [Design Form Link](http://link)
 * What hardware is needed?
   - Robot with NavX
 * What software is needed?

Test Cases:
 * Robot stops at exactly 90
 * Test Case 2

 Done Criteria:
  * Pull request
  * Manager approval
  * Mentor approval

  Make sure this issue is associated with a Milestone!

**Comment by jkoritzinsky** [comment]
Is this for the autonomous NavX turning?

**Comment by Noah-Kennedy** [comment]
Yes.
