### ISSUE TITLE
Install FRC Update suite to each laptop

### ISSUE THREAD

**Issue by koritzinsky** [NicoletFEAR/Steamworks-2017#4]
Description of the story:  As a developer, I need to install the FRC update suite on each laptop so that I can program and use the driver station for this build season.

- [ ] Pull Request Required - none

Ready Criteria:
 * Update suite is downloaded to each laptop
* Password is available after kick-off
* Hardware and Software configuration list

 * What hardware is needed? Laptops
 
   
 * What software is needed? See above

 Done Criteria:
  * Update suite is installed without errors on both school laptops
  * Software and hardware configuration sheet is updated with date & your initials on hard drive
  * Label (from label maker) is placed on each laptop with the name of the software, version, and date

  Make sure this issue is associated with a Milestone!

**Comment by jkoritzinsky** [comment]
Sign off
