### ISSUE TITLE
Install router configuration utility on each laptop

### ISSUE THREAD

**Issue by koritzinsky** [NicoletFEAR/Steamworks-2017#5]
Description of the story:  Install the router configuration utility to each laptop.  This is used to set up the router.

- [ ] Pull Request Required

Ready Criteria:

Router configuration software is available from screen steps live.
Router configuration may already downloaded to one of the laptops

What hardware is needed? Laptops

What software is needed? See above

Done Criteria:

Router configuration utility is installed on both school laptops
Software and hardware configuration sheet is updated with date & your initials on shared drive

  Make sure this issue is associated with a Milestone!

**Comment by CodeforEvolution** [comment]
Already Installed on Laptop 4, I'm done with this!
