### ISSUE TITLE
Install WPI plug-ins into eclipse

### ISSUE THREAD

**Issue by koritzinsky** [NicoletFEAR/Steamworks-2017#6]
Description of the story:  Install WPI plug-ins and Talon SRX into eclipse so that programmers can develop the 2017 robot.

- [ ] Pull Request Required - no

Ready Criteria:
 * Plug-ins are available on screen-steps live
 * What hardware is needed?
   - laptop
  
 * What software is needed?

 Done Criteria:
  * Plug-ins are successfully loaded on each laptop
  * Talon SRX software installed on each laptop
  * Show mentor that plug in is installed
* update hardware and software configuration list with plug-in version & date & your initials

  Make sure this issue is associated with a Milestone!

**Comment by jkoritzinsky** [comment]
Sign off
